"""initial

Revision ID: b2360e1d958c
Revises: 
Create Date: 2026-05-20 09:55:25.266388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2360e1d958c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_identification_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('user_image_key', sa.String(length=500), nullable=False),
    sa.Column('identification_confidence', sa.Float(), nullable=False),
    sa.Column('identification_source', sa.String(length=50), nullable=False),
    sa.Column('raw_response', sa.Enum(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_deep_analysis', sa.Boolean(), nullable=False),
    sa.Column('has_nutritional_analysis', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_identification_samples_scientific_name'), 'plant_identification_samples', ['scientific_name'], unique=False)
    op.create_index(op.f('ix_plant_identification_samples_status'), 'plant_identification_samples', ['status'], unique=False)
    op.create_index(op.f('ix_plant_identification_samples_user_id'), 'plant_identification_samples', ['user_id'], unique=False)
    op.create_table('plant_nutritional',
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('tea_preparation', sa.String(length=1000), nullable=True),
    sa.Column('tea_benefits', sa.String(length=1000), nullable=True),
    sa.Column('food_recipe_name', sa.String(length=255), nullable=True),
    sa.Column('food_recipe_ingredients', sa.Enum(), nullable=True),
    sa.Column('medicinal_uses', sa.String(length=1000), nullable=True),
    sa.Column('seasoning_pairings', sa.String(length=500), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('scientific_name')
    )
    op.create_table('plant_reference_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('source', sa.Enum('kindwise_similar', 'user_confirmed', name='imagesource'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_reference_images_scientific_name'), 'plant_reference_images', ['scientific_name'], unique=False)
    op.create_table('plant_species',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('enrichment_status', sa.Enum('pending', 'enriched', 'failed', name='enrichmentstatus'), nullable=False),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('genus', sa.String(length=100), nullable=True),
    sa.Column('order', sa.String(length=100), nullable=True),
    sa.Column('plant_class', sa.String(length=100), nullable=True),
    sa.Column('common_names', sa.JSON(), nullable=True),
    sa.Column('kindwise_entity_id', sa.String(length=100), nullable=True),
    sa.Column('gbif_id', sa.String(length=100), nullable=True),
    sa.Column('is_edible', sa.Boolean(), nullable=True),
    sa.Column('water_frequency_per_week', sa.Integer(), nullable=True),
    sa.Column('light_requirement', sa.Enum('low', 'indirect', 'direct', 'full_sun', name='lightrequirement'), nullable=True),
    sa.Column('soil_type', sa.Enum('sandy', 'clay', 'loamy', 'well_draining', name='soiltype'), nullable=True),
    sa.Column('best_planting_season', sa.String(length=50), nullable=True),
    sa.Column('origin_country', sa.String(length=100), nullable=True),
    sa.Column('habitat', sa.String(length=255), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrichment_source', sa.Enum('gemini', 'kindwise', 'plantnet', name='enrichmentsource'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_species_enrichment_status'), 'plant_species', ['enrichment_status'], unique=False)
    op.create_index(op.f('ix_plant_species_scientific_name'), 'plant_species', ['scientific_name'], unique=True)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_code', sa.String(length=100), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_plants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('identification_confidence', sa.Float(), nullable=False),
    sa.Column('identification_source', sa.Enum('kindwise', 'plantnet', 'consensus', name='identificationsource'), nullable=False),
    sa.Column('status', sa.Enum('pending_enrichment', 'identified', 'enriched', name='identificationstatus'), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('primary_image_url', sa.String(length=500), nullable=True),
    sa.Column('last_watered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=False),
    sa.Column('streak_last_action_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('care_type', sa.String(length=50), nullable=False),
    sa.Column('care_interval_days', sa.Integer(), nullable=False),
    sa.Column('care_is_active', sa.Boolean(), nullable=False),
    sa.Column('care_next_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('care_last_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('care_climate_adjusted', sa.Boolean(), nullable=False),
    sa.Column('care_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_plants_user_id'), 'user_plants', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('location_country', sa.String(length=2), nullable=False),
    sa.Column('location_state', sa.String(length=100), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('subscription', sa.Enum(('FREE', 3, 3), ('PRO', 50, 30), name='subscriptiontier'), nullable=False),
    sa.Column('tokens_used_today', sa.Integer(), nullable=False),
    sa.Column('garden_count', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=True),
    sa.Column('fcm_token_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('health_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_plant_id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('diagnosed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vitality_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('healthy', 'low', 'moderate', 'high', 'critical', name='healthseverity'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('image_key', sa.String(length=500), nullable=True),
    sa.Column('issues_detected', sa.JSON(), nullable=True),
    sa.Column('treatment_plan', sa.JSON(), nullable=True),
    sa.Column('recovery_estimate_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user_plant_id'], ['user_plants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_records_scientific_name'), 'health_records', ['scientific_name'], unique=False)
    op.create_index(op.f('ix_health_records_user_plant_id'), 'health_records', ['user_plant_id'], unique=False)
    op.create_table('health_identification_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('health_record_id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('user_image_key', sa.String(length=500), nullable=False),
    sa.Column('reference_image_keys', sa.JSON(), nullable=False),
    sa.Column('vitality_score', sa.Float(), nullable=False),
    sa.Column('issues_detected', sa.JSON(), nullable=False),
    sa.Column('treatment_plan', sa.JSON(), nullable=False),
    sa.Column('identification_source', sa.String(length=50), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', name='healthsamplestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_estimate_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['health_record_id'], ['health_records.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_identification_samples_health_record_id'), 'health_identification_samples', ['health_record_id'], unique=True)
    op.create_index(op.f('ix_health_identification_samples_scientific_name'), 'health_identification_samples', ['scientific_name'], unique=False)
    op.create_index(op.f('ix_health_identification_samples_status'), 'health_identification_samples', ['status'], unique=False)
    op.create_index(op.f('ix_health_identification_samples_user_id'), 'health_identification_samples', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_identification_samples_user_id'), table_name='health_identification_samples')
    op.drop_index(op.f('ix_health_identification_samples_status'), table_name='health_identification_samples')
    op.drop_index(op.f('ix_health_identification_samples_scientific_name'), table_name='health_identification_samples')
    op.drop_index(op.f('ix_health_identification_samples_health_record_id'), table_name='health_identification_samples')
    op.drop_table('health_identification_samples')
    op.drop_index(op.f('ix_health_records_user_plant_id'), table_name='health_records')
    op.drop_index(op.f('ix_health_records_scientific_name'), table_name='health_records')
    op.drop_table('health_records')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_plants_user_id'), table_name='user_plants')
    op.drop_table('user_plants')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_plant_species_scientific_name'), table_name='plant_species')
    op.drop_index(op.f('ix_plant_species_enrichment_status'), table_name='plant_species')
    op.drop_table('plant_species')
    op.drop_index(op.f('ix_plant_reference_images_scientific_name'), table_name='plant_reference_images')
    op.drop_table('plant_reference_images')
    op.drop_table('plant_nutritional')
    op.drop_index(op.f('ix_plant_identification_samples_user_id'), table_name='plant_identification_samples')
    op.drop_index(op.f('ix_plant_identification_samples_status'), table_name='plant_identification_samples')
    op.drop_index(op.f('ix_plant_identification_samples_scientific_name'), table_name='plant_identification_samples')
    op.drop_table('plant_identification_samples')
    # ### end Alembic commands ###
